package com.ycy.center.dao.mapper;

import com.ycy.center.dao.entity.YcyTable;
import com.ycy.center.dao.entity.YcyTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YcyTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ycy_table
     *
     * @mbggenerated Mon Nov 20 22:54:31 CST 2017
     */
    int countByExample(YcyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ycy_table
     *
     * @mbggenerated Mon Nov 20 22:54:31 CST 2017
     */
    int deleteByExample(YcyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ycy_table
     *
     * @mbggenerated Mon Nov 20 22:54:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ycy_table
     *
     * @mbggenerated Mon Nov 20 22:54:31 CST 2017
     */
    int insert(YcyTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ycy_table
     *
     * @mbggenerated Mon Nov 20 22:54:31 CST 2017
     */
    int insertSelective(YcyTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ycy_table
     *
     * @mbggenerated Mon Nov 20 22:54:31 CST 2017
     */
    List<YcyTable> selectByExample(YcyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ycy_table
     *
     * @mbggenerated Mon Nov 20 22:54:31 CST 2017
     */
    YcyTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ycy_table
     *
     * @mbggenerated Mon Nov 20 22:54:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") YcyTable record, @Param("example") YcyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ycy_table
     *
     * @mbggenerated Mon Nov 20 22:54:31 CST 2017
     */
    int updateByExample(@Param("record") YcyTable record, @Param("example") YcyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ycy_table
     *
     * @mbggenerated Mon Nov 20 22:54:31 CST 2017
     */
    int updateByPrimaryKeySelective(YcyTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ycy_table
     *
     * @mbggenerated Mon Nov 20 22:54:31 CST 2017
     */
    int updateByPrimaryKey(YcyTable record);
}